services:
  game:
    image: game_project_img
    build:
      context: .
      dockerfile: Docker/backFastify/Dockerfile
      
    ports:
      - "3000:3000"
    environment:
      - HOST_IP=192.168.1.13  # IP a definir manuellement pour telephone

    command:  sh -c "npm run build && npm run dev"

    volumes:
      - ./code/:/app/

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 10s
    container_name: game_project_cont
